In [8]:
import numpy as np
import time
n=100
m=100
l=100
k=9
N=np.random.randint(k, size=(n,m))
M=np.random.randint(k, size=(n,m))
print(N,"\n")

print(M,"\n")
s = (m, l)
###
res1 = np.zeros(s)
stime1 = time.time()
for i in range(len(N)):
   for j in range(len(M[0])):
       for k in range(len(M)):
           result1[i][j] += N[i][k] * M[k][j]
ftime1 = time.time()
print("Time  =", ftime1 - stime1, "\n")
res2 = np.zeros(s)
stime2 = time.time()
res2 = np.dot(N,M)
ftime2 = time.time()
print("Time dot  =", ftime2 - stime2, "\n")
print("Difference  =", ftime1 - stime1 - ftime2 + stime2, "\n" )

[[8 6 2 ... 0 4 8]
 [8 4 8 ... 3 5 3]
 [0 1 8 ... 7 6 0]
 ...
 [4 2 7 ... 2 1 3]
 [7 7 8 ... 5 4 3]
 [6 4 3 ... 3 7 1]] 

[[5 1 2 ... 0 1 0]
 [0 0 3 ... 0 8 2]
 [6 2 8 ... 6 0 0]
 ...
 [5 4 8 ... 3 0 5]
 [3 7 5 ... 5 5 4]
 [2 1 4 ... 5 1 0]] 

Time  = 1.3635103702545166 

Time dot  = 0.0009984970092773438 

Difference  = 1.3625118732452393 

